name: mech_doc
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.3







dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3  
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  google_fonts: ^6.2.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  iconsax: ^0.0.8
  eva_icons_flutter: ^3.1.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4
  lottie: ^3.1.3

  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  
  
  uses-material-design: true
  
  assets:
    - assets/icons/icon.png
    - assets/icons/plumber.png
    - assets/icons/service_icon.png
    - assets/icons/star_icon.png
    - assets/icons/profile.png
    - assets/icons/notification.png
    - assets/icons/boss.png
    - assets/icons/edit.png
    - assets/icons/image.png
    - assets/icons/buisness_man.png
    - assets/icons/check.png
    - assets/icons/chat.png
    - assets/icons/wallet.png
    - assets/icons/home.png
    - assets/icons/worker.png
    - assets/icons/playstore-icon.png
    - assets/icons/mechanic.png
    - assets/icons/profile_image.jpg
    - assets/icons/person.png
    - assets/animations/Message Sent.json
    - assets/animations/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
